---1. How many employees are there in each department?

SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY EMPLOYEE_COUNT DESC;

---2. Who are the top 5 highest-paid employees? Display their names, salary, department, and job title.

SELECT * FROM (
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,
               J.JOB_TITLE,
               D.DEPARTMENT_NAME,
               E.SALARY
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY E.SALARY DESC
)
WHERE ROWNUM<=5;

---3.What is the average salary of employees in each department? 

SELECT D.DEPARTMENT_NAME, ROUND(AVG(E.SALARY),2) AS AVG_SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
GROUP BY D.DEPARTMENT_NAME
ORDER BY AVG(E.SALARY) DESC;

----4.How many employees work in each country?

SELECT C.COUNTRY_NAME, COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM EMPLOYEES E
JOIN DEPARTMENTS D  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY C.COUNTRY_NAME
ORDER BY EMPLOYEE_COUNT DESC;

---5. List each manager with the count of employees reporting to them.

SELECT M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER_NAME,
       COUNT(E.EMPLOYEE_ID) AS TEAM_SIZE
FROM EMPLOYEES E
JOIN  EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY  M.FIRST_NAME , M.LAST_NAME 
ORDER BY TEAM_SIZE DESC;

---6.Which job roles are most common in the company, and how many employees work in each

SELECT J.JOB_TITLE, COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
ORDER BY EMPLOYEE_COUNT DESC;

---7.Show employee name, job, department, city, and country they are located in.

SELECT  E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,
            J.JOB_TITLE,
            D.DEPARTMENT_NAME,
            L.CITY,
            C.COUNTRY_NAME
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
JOIN DEPARTMENTS D  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID

---8.Are there any departments that currently have no employees?

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN
(
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
)

---9.Who joined the company in the last 6 months?

SELECT  FIRST_NAME || ' ' || LAST_NAME AS EMPLOYEE_NAME,
                HIRE_DATE,    
                DEPARTMENT_ID
FROM EMPLOYEES
WHERE HIRE_DATE >=ADD_MONTHS(SYSDATE,-6)

---10.Show the average experience (in years) of employees in each department. 

SELECT D.DEPARTMENT_NAME,
            ROUND(AVG(MONTHS_BETWEEN(SYSDATE,E.HIRE_DATE)/12),2) AS AVG_EXP_YEARS
 FROM EMPLOYEES E      
 JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME
 ORDER BY AVG_EXP_YEARS DESC;
                