-- Sample rows from each table
SELECT * FROM employees FETCH FIRST 5 ROWS ONLY;
SELECT * FROM departments FETCH FIRST 5 ROWS ONLY;
SELECT * FROM jobs FETCH FIRST 5 ROWS ONLY;
SELECT * FROM locations FETCH FIRST 5 ROWS ONLY;
SELECT * FROM countries FETCH FIRST 5 ROWS ONLY;
SELECT * FROM regions FETCH FIRST 5 ROWS ONLY;

-- Count of records in each table
SELECT 'EMPLOYEES' AS table_name, COUNT(*) FROM employees
UNION ALL
SELECT 'DEPARTMENTS', COUNT(*) FROM departments
UNION ALL
SELECT 'JOBS', COUNT(*) FROM jobs
UNION ALL
SELECT 'LOCATIONS', COUNT(*) FROM locations
UNION ALL
SELECT 'COUNTRIES', COUNT(*) FROM countries
UNION ALL
SELECT 'REGIONS', COUNT(*) FROM regions;